export const ImageConst = {
  homeFocused: require('../assets/images/home.png'),
  homeUnfocused: require('../assets/images/home2.png'),
  categoryFocused: require('../assets/images/category2.png'),
  categoryUnFocused: require('../assets/images/category.png'),
  cart: require('../assets/images/cart.png'),
  cartUnFocused: require('../assets/images/cart2.png'),
  profle: require('../assets/images/profile.png'),
  pin: require('../assets/images/pin.png'),
  user: require('../assets/images/user.png'),
  veg: require('../assets/images/veg.png'),
  fish: require('../assets/images/fish.png'),
  carrot: require('../assets/images/carrot.png'),
  orange: require('../assets/images/orange.png'),
  raddish: require('../assets/images/raddish.png'),
  tomatoes: require('../assets/images/tomatoes.png'),
  pepper: require('../assets/images/pepper.png'),
  corn: require('../assets/images/corn.png'),
  brocolli: require('../assets/images/brocolli.png'),
  avacado: require('../assets/images/avacado.png'),
  banana: require('../assets/images/banana.png'),
  backarrow: require('../assets/images/arrow.png'),
  plus: require('../assets/images/add2.png'),
  minus: require('../assets/images/minus.png'),
  heart: require('../assets/images/heart.png'),
};
